models/error.py
from flask import jsonify

from db import db

class Error(db.Model):
    """ 
    Error MODEL

    """
    
    __tablename__ = 'errors'

    id = db.Column(db.Integer, primary_key=True)
    part_number = db.Column(db.String)
    date = db.Column(db.Date, nullable=False)
    machine = db.Column(db.String)
    description = db.Column(db.String, nullable=False)
    root_cause = db.Column(db.String)
    notes = db.Column(db.String)
    name = db.Column(db.String)
    
    def __repr__(self): 
        return f"<Error #: {self.id}, Date: {self.date}, Description: {self.description}>"

    @staticmethod
    def many_to_json(data):
        errors = []
        
        for error in data:
            errors.append({
                "id" : error.id,
                "part_number": error.part_number,
                "description": error.description,
                "date" : error.date,
                "machine" : error.machine,
                "root_cause" : error.root_cause,
                "notes" : error.notes,
                "name" : error.name
            })
            
        return errors

routes/errors.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, g, jsonify, request, send_file
from db import db

from models.error import Error
from models.file import File
from models.forms import AddError, EditError

from datetime import datetime
from utilities import upload_error_file, list_all_objects_version, create_presigned_url

errors = Blueprint(
    'errors',
    __name__,
    static_folder='../../static',
    template_folder='../../templates/app',
    url_prefix='/errors'
    )


@errors.route("/")
def error_log():
    errors = Error.query.order_by(Error.date.desc()).all()
    
    for error in errors:
        error.date = error.date.strftime("%m/%d/%Y")
        
    return render_template("/error_log/error-log.html", errors=errors)    


@errors.route("/data")
def get_data():
    
    errors = Error.query.order_by(Error.date.desc()).all()
    errors = Error.many_to_json(errors)
    
    return errors


@errors.route("/add", methods=["GET", "POST"])
def add_to_errors():
    
    form = AddError()
    
    if form.validate_on_submit():
        
        new_error = Error(
            part_number = form.part_number.data,
            date = datetime.today().strftime("%m-%d-%Y"),
            machine = form.machine.data,
            description = form.description.data,
            root_cause = form.root_cause.data,
            notes = form.notes.data,
            name = form.name.data
        )
        
        db.session.add(new_error)
        db.session.commit()
        
        return redirect(url_for('errors.error_log'))
    
    return render_template("/error_log/add-error.html", form=form)


@errors.route("/edit/<error_id>", methods=["GET", "POST"])
def edit_error(error_id):
    
    error = Error.query.filter_by(id=error_id).one()
    
    form = EditError(obj=error)
    
    if form.validate_on_submit():
       
        error.part_number = form.part_number.data or error.part_number,
        error.machine = form.machine.data or error.machine,
        error.description = form.description.data or error.description,
        error.root_cause = form.root_cause.data or error.root_cause,
        error.notes = form.notes.data or error.notes,
        error.name = form.name.data or error.name
         
        db.session.commit()
        
        return redirect(url_for('errors.show_error', id=error_id))
    
    return render_template("/error_log/edit-error.html", form=form, error_id=error.id)


@errors.route("/<id>")
def show_error(id):
    
    error = Error.query.filter_by(id=id).one()
    files = File.query.filter_by(error_id=id).all()
    
    for file in files:
        # Create presigned URLS
        file.presigned_url = create_presigned_url(file.file_name, file.version)
        
    return render_template('/error_log/error.html', error=error, files=files)


@errors.route("/<id>/add", methods=["GET", "POST"])
def add_file(id):
    if request.method=="POST" :
        try:
            files = request.files.getlist('images')
            
            for file in files:
                upload_error_file(file=file, filename=file.filename)
                
                response = list_all_objects_version(file.filename)
                new_file = File(file_name=file.filename, error_id=id)
                
                try:
                    new_file.version = response["Versions"][0]["VersionId"]
                except:
                    new_file.version = '0'
                
                db.session.add(new_file)
                db.session.commit()

        except Exception as e:
            print(e)
            
        return redirect(url_for('errors.show_error', id=id))
    return render_template('/error_log/add-file.html', id=id)

templates/error_log/add-error.html
{% extends 'base.html' %}
{% block title %} Add Error {%endblock%}

{% block content %}

<div class="container my-4" id="alerts">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          <ul class='flashes'>
          {% for category, message in messages %}
            <div class="alert alert-{{category}} " id="flashed">
              {{ message }}
            </div>
          {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
    </div>
    <div class="col-3"></div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h1 class="text-center">Add Error</h1>
      <form action="{{ url_for('errors.add_to_errors') }}" method="POST">
        {{ form.hidden_tag() }}  
          {% for field in form
                  if field.widget.input_type != 'hidden' %}

                <div class="field">
                  {{ field.label(class_='form-label') }}
                  <div class="control">
                  {{ field(class='form-control') }}
                  </div>
                </div>
                {% for error in field.errors %}
                  {{ error }}
                {% endfor %}
              </p>

            {% endfor %}
          

          <div class="row">
            <div class="col-6">
              <button class="btn btn-primary" type="submit" style="width:100%;">Add</button>
            </div>
            <div class="col-6">
              <a href="{{url_for('errors.error_log')}}"><button class="btn btn-danger" type="button"  style="width:100%;">Cancel</button></a>
            </div>
          </div>
            
        </form>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>  

{% endblock %}

templates/error_log/add-file.html
{% extends 'base.html' %} {% block title %} Add Image {%endblock%} {% block
content %}

<div class="container my-4" id="alerts">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <ul class="flashes">
        {% for category, message in messages %}
        <div class="alert alert-{{category}} " id="flashed">{{ message }}</div>
        {% endfor %}
      </ul>
      {% endif %} {% endwith %}
    </div>
    <div class="col-3"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h1 class="text-center">Add Image</h1>
      <form
        action="{{ url_for('errors.add_file', id=id) }}"
        method="POST"
        enctype="multipart/form-data"
      >
        <div class="mb-3">
          <label for="images" class="form-label">Select your images</label>
          <input
            class="form-control"
            type="file"
            id="images"
            name="images"
            multiple
          />
        </div>

        <div class="row">
          <div class="col-6">
            <button class="btn btn-primary" type="submit" style="width: 100%">
              Add File
            </button>
          </div>
          <div class="col-6">
            <a href="{{url_for('errors.show_error', id=id)}}"
              ><button class="btn btn-danger" type="submit" style="width: 100%">
                Cancel
              </button></a
            >
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

<script src="/static/hubs/production.js"></script>
{% endblock %}

templates/error_log/edit-error.html
{% extends 'base.html' %}
{% block title %} Add Error {%endblock%}

{% block content %}

<div class="container my-4" id="alerts">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          <ul class='flashes'>
          {% for category, message in messages %}
            <div class="alert alert-{{category}} " id="flashed">
              {{ message }}
            </div>
          {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
    </div>
    <div class="col-3"></div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h1 class="text-center">Edit</h1>
      <form action="{{ url_for('errors.edit_error', error_id=error_id) }}" method="POST">
        {{ form.hidden_tag() }}  
          {% for field in form
                  if field.widget.input_type != 'hidden' %}

                <div class="field">
                  {{ field.label(class_='form-label') }}
                  <div class="control">
                  {{ field(class='form-control') }}
                  </div>
                </div>
                {% for error in field.errors %}
                  {{ error }}
                {% endfor %}
              </p>

            {% endfor %}
          

          <div class="row">
            <div class="col-6">
              <button class="btn btn-primary" type="submit" style="width:100%;">Edit</button>
            </div>
            <div class="col-6">
              <a href="{{ url_for('errors.show_error', id=error_id) }}"><button class="btn btn-danger" type="button"  style="width:100%;">Cancel</button></a>
            </div>
          </div>
            
        </form>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>  

{% endblock %}

templates/error_log/error-log.html
{% extends 'base.html' %} {% block title %} Error Log {% endblock %} {% block
content %}
<h1 class="text-center my-4">Error Log</h1>
<div class="container my-5">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10">
      <nav class="nav nav-pills nav-fill">
        <a class="nav-link mat-butts mat-butts-active mx-1" href="#">LASERS</a>
        <a class="nav-link mat-butts mx-1" href="#">FORMING</a>
        <a class="nav-link mat-butts mx-1" href="#">OTHER</a>
      </nav>
    </div>
    <div class="col-1"></div>
  </div>
</div>

<div class="container">
  <div class="row my-5">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table my-3 table-hover">
              <thead>
                <tr>
                  <th scope="col" class="text-center"></th>
                  <th scope="col" class="text-center">Nest/Part Number</th>
                  <th scope="col" class="text-center">Machine</th>
                  <th scope="col" class="text-center">Description</th>
                  <th scope="col" class="text-center">Root Cause</th>
                  <th scope="col" class="text-center">Notes</th>
                  <th scope="col" class="text-center">Logged By</th>
                  <th scope="col" class="text-center">Date</th>
                  <th scope="col" class="text-center">
                    <a href="{{url_for('errors.add_to_errors')}}"
                      ><i class="fa-solid fa-square-plus"></i
                    ></a>
                  </th>
                </tr>
              </thead>
              <tbody id="results">
                {% if errors %} {% for error in errors %} {% if 'Laser' in
                error.machine %}
                <tr>
                  <td class="text-center align-middle">
                    <a
                      href="{{url_for('errors.edit_error', error_id=error.id)}}"
                      ><i class="fa-solid fa-pencil"></i
                    ></a>
                  </td>
                  <td class="text-center align-middle">
                    {{ error.part_number}}
                  </td>
                  <td class="text-center align-middle">{{ error.machine}}</td>
                  <td class="text-center align-middle">
                    {{ error.description}}
                  </td>
                  <td class="text-center align-middle">
                    {{ error.root_cause}}
                  </td>
                  <td class="text-center align-middle">{{ error.notes}}</td>
                  <td class="text-center align-middle">{{ error.name}}</td>
                  <td class="text-center align-middle">{{ error.date}}</td>
                  <td class="text-center align-middle">
                    <a href="{{url_for('errors.show_error', id=error.id)}}"
                      ><i class="fa-solid fa-circle-info"></i
                    ></a>
                  </td>
                </tr>
                {% endif %} {% endfor %} {% endif %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="/static/production/error-log.js"></script>
<script src="/static/hubs/production.js"></script>

{% endblock %}

templates/error_log/error.html
{%extends 'base.html'%} {%block title%}{{error.id}}{%endblock%} {%block
content%}

<div class="container my-4" id="alerts">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <ul class="flashes">
        {% for category, message in messages %}
        <div class="alert alert-{{category}} " id="flashed">{{ message }}</div>
        {% endfor %}
      </ul>
      {% endif %} {% endwith %}
    </div>
    <div class="col-3"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-2">
      <a href="{{url_for('errors.error_log')}}"
        ><button class="btn btn-primary" style="width: 100%">Back</button></a
      >
    </div>
    <div class="col-8"></div>
    <div class="col-2">
      <a href="{{url_for('errors.edit_error', error_id=error.id)}}"
        ><button class="btn btn-primary" style="width: 100%">Edit</button></a
      >
    </div>
  </div>
</div>

<div class="container">
  <div class="row my-5">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table my-3 table-hover">
              <thead>
                <tr>
                  <th scope="col" class="text-center">Part Number</th>
                  <th scope="col" class="text-center">Description</th>
                  <th scope="col" class="text-center">Machine</th>
                  <th scope="col" class="text-center">Root Cause</th>
                  <th scope="col" class="text-center">Notes</th>
                  <th scope="col" class="text-center">Date</th>
                  <th scope="col" class="text-center">Logged By</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="text-center">{{ error.part_number}}</td>
                  <td class="text-center">{{ error.description}}</td>
                  <td class="text-center">{{ error.machine}}</td>
                  <td class="text-center">{{ error.root_cause}}</td>
                  <td class="text-center">{{ error.notes}}</td>

                  <td class="text-center">
                    {{ error.date.strftime('%m-%d-%Y')}}
                  </td>
                  <td class="text-center">{{error.name}}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row my-5">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title text-center">Pictures</h5>
          <a href="{{url_for('errors.add_file', id=error.id)}}"
            ><i class="fa-solid fa-square-plus"></i
          ></a>

          {% if files %} {% for file in files %}
          <h6>{{file.file_name}}</h6>

          <a href="{{file.presigned_url}}"
            ><img
              class="img-fluid"
              src="{{file.presigned_url}}"
              alt="{{file.file_name}}"
          /></a>
          <hr />
          {% endfor %} {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{%endblock%}