models/requests.py
from flask import jsonify

from db import db


class Request(db.Model):
    """ 
    Request MODEL

    """

    __tablename__ = 'requests'

    id = db.Column(db.Integer, primary_key=True)
    to_change = db.Column(db.String)
    date = db.Column(db.Date, default=db.func.current_date())
    description = db.Column(db.String, nullable=False)
    requested_by = db.Column(db.String, nullable=False)
    request_type = db.Column(db.String, nullable=False)
    job_number = db.Column(db.String)
    date_completed = db.Column(db.Date, nullable=True)
    
    def __repr__(self): 
        return f"<Request #: {self.id}, What to change: {self.to_change}, Description: {self.description}, Requester: {self.requested_by}, Type: {self.request_type}>"
    
    @staticmethod
    def many_to_json(data):
        requests = []
        
        for request in data:
            requests.append({
                "id" : request.id,
                "to_change": request.to_change,
                "description": request.description,
                "requested_by" : request.requested_by,
                "request_type" : request.request_type,
                "job_number" : request.job_number,
                "date_completed" : request.date_completed.strftime("%m/%d/%Y") if request.date_completed else ""
            })
            
        return requests

routes/general.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, g, jsonify, request
from sqlalchemy import select

from models.materials import Materials, Blanks
from models.part import Part
from models.forms import CreateIssueForm

from utilities import get_issues, post_issue

from db import db

general = Blueprint(
    'general',
    __name__,
    static_folder='../../static',
    template_folder='../../templates',
    url_prefix='/'
    )

@general.route("/nesting_calculator")
def nesting_calculator():
    return render_template("/misc/nesting-calculator.html")


@general.route("/blanks/inventory", methods=['GET', 'POST', 'DELETE'])
def blanks_inventory():
    if request.method == 'GET': # Get all blanks in inventory
        blanks = get_blanks_data()
        materials = get_materials_data()
        
        blank_material_names = set()
        [blank_material_names.add(blank['material_name']) for blank in blanks]    # Set comprehension to get unique material names
        
        material_names = set()
        [material_names.add(material['material_name']) for material in materials] # Set comprehension to get unique material names
        
        return render_template(
            "misc/blanks.html", 
            blanks=blanks, 
            materials=materials, 
            material_names=material_names, 
            blank_material_names=blank_material_names)

    if request.method == 'POST': # Add new blank to inventory
        data = request.get_json() 
        try:
            material_id = Materials.query.filter_by(
                material_name=data['material'], gauge=data['gauge']).first().id
        except Exception as e:
            new_material = Materials(
                material_name=data['material'],
                gauge=data['gauge']
            )
            db.session.add(new_material)
            db.session.commit()
            
            material_id = Materials.query.filter_by(
                material_name=data['material'], gauge=data['gauge']).first().id
            
        blanks = Blanks.query.filter_by(
            material_id=material_id, length=data['length'], width=data['width']).first()
        
        if blanks:
            blanks.quantity += int(data['quantity']) or 1
            db.session.commit()
        else:
            try:
                new_blank = Blanks(
                    material_id=material_id,
                    length=data['length'],
                    width=data['width'],
                    quantity=int(data['quantity']) or 1
                )
                db.session.add(new_blank)
                db.session.commit()
            except Exception as e:
                print(e)
                return jsonify({'success': False, 'message': 'Error adding blank'})
        
        return jsonify({'success': True})
    
    if request.method == 'DELETE': # Delete blank from inventory
        data = request.get_json()
        
        material_id = Materials.query.filter_by(
            material_name=data['material'], gauge=data['gauge']).first().id

        blanks = Blanks.query.filter_by(
            material_id=material_id, length=data['length'], width=data['width']).first()
        
        blanks.quantity -= 1
        
        if blanks.quantity:
            db.session.commit()
        else:
            db.session.delete(blanks)
            db.session.commit()
            return jsonify({'success': True, 'delete': True})
        
        return jsonify({'success': True, 'delete': False})


@general.route("/blanks/data")
def get_blanks_data():
    blanks = Blanks.query.order_by("material_id").all()
    blanks = Blanks.many_to_json(blanks)
    
    return blanks


@general.route("/materials/data")
def get_materials_data():
    materials = Materials.query.all()
    materials = Materials.many_to_json(materials)
    
    return materials


@general.route("/eco")
def eco_viewer():
    
    eco_data = get_eco_data()
    
    return render_template("/misc/eco.html", eco_data=eco_data)


@general.route("/eco/data")
def get_eco_data():
    parts = Part.query.order_by(Part.eco_number, Part.part_number.desc()).all()    
    parts = Part.many_to_json(parts)
    
    return parts


@general.route("/eco/data/obsolete")
def get_obsolete_eco_data():
    statement = select(Part.replaces).where(Part.replaces.is_not(None))
    parts = db.session.execute(statement)
    obsolete = []
    
    for each in parts.scalars():
        if '&' in each:
            splits = each.split(' & ')
            for split in splits:
                obsolete.append(split)
            continue    
        
        if len(each) > 12:
            each = each.split(' ')
            for split in each:
                obsolete.append(split)
            continue
        
        if 'F' in each:
            each = each.replace('F', '')
            
        obsolete.append(each)
    
    return obsolete


@general.route("/data_explorer")
def data_explorer():
    return render_template("/misc/explorer.html")


@general.route("/issues")
def issues():
    issues = get_issues()
    
    return render_template("/misc/issues.html", issues=issues)

@general.route("/issues/create", methods=['GET', 'POST'])
def create_issue():
    form = CreateIssueForm()
    
    if request.method == 'GET':
        return render_template("/misc/create-issue.html", form=form)
    
    if form.validate_on_submit():
        try:
            post_issue(form.data)
        except Exception as e:
            flash('Error creating issue. Try again.', 'danger')
            print(e)
            
    return redirect(url_for('general.issues'))

@general.route("/issues/data")
def all_issues():
    data = get_issues()
    issues = []
    
    for each in data:
        if each.pull_request:
            continue
        
        issues.append({
            "title": each.title, 
            "body": each.body, 
            "created_at": each.created_at.strftime("%m/%d/%y"),
            "updated_at": each.updated_at.strftime("%m/%d/%y") if each.updated_at else None,
            "comments": each.comments,
            "state": each.state,
            "closed_at": each.closed_at.strftime("%m/%d/%y") if each.closed_at else None,
            })
    
    return issues

routes/requests.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, g, jsonify, request, send_file
from models.requests import Request
from models.forms import AddRequest
from db import db
from datetime import datetime
from utilities import email

COMPLETED_DATE_LIMIT = 5

requests = Blueprint(
    'requests',
    __name__,
    static_folder='../../static',
    template_folder='../../templates/app',
    url_prefix='/requests'
    )


@requests.route("/", methods=["GET", "POST", "DELETE"])
def requesting():
    form = AddRequest()
    today = datetime.now()
    
    if request.method == "GET": # Get all requests
        requests = Request.query.order_by(Request.date_completed.desc()).all()

        for req in requests:
            try:
                # Delete requests that have been completed for 5 days
                if (today - datetime.combine(
                    req.date_completed, datetime.min.time())).days >= COMPLETED_DATE_LIMIT: 
                    db.session.delete(req)
                    db.session.commit() 
            except Exception as e:
                print(e)
                pass        
        
        return render_template("misc/requests.html", form=form, requests=requests)

    if request.method == "POST": # Add new request
        data = request.get_json()
        
        new_request = Request(
            to_change=data['to_change'],
            description=data['description'],
            requested_by=data['requested_by'],
            request_type=data['request_type'],
            job_number=data.get('job_number'))

        db.session.add(new_request)
        db.session.commit()
        
        email(data) # Send email to programming team
        
        return jsonify({'success': True, 'message': 'Request added'})
    
    if request.method == "DELETE": # Stage request for deletion
        data = request.get_json()
        
        req = Request.query.get(data['id'])
        req.date_completed = today
        req.job_number = data.get('job_number')
        
        db.session.commit()
        
        return jsonify({'success': True, 'message': 'Request staged for deletion'})

templates/misc/blanks.html
{% extends 'base.html' %} {% block title %}Blanks Management{% endblock %} {%
block content %}
<div class="mb-3" id="alerts"></div>
<h3 class="text-center my-3">Add Blank</h3>
<div class="container my-3">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
      <div class="container">
        <form class="row g-3">
          <div class="col-md-4">
            <label for="gauge" class="form-label">Gauge</label>
            <input type="text" class="form-control" id="gauge" required />
          </div>
          <div class="col-md-4">
            <label for="material" class="form-label">Material</label>
            <select id="material" class="form-select" required>
              <option selected>Choose...</option>
              {% for material in material_names %}
              <option>{{ material }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-md-4">
            <label for="quantity" class="form-label">Qty.</label>
            <input type="text" class="form-control" id="quantity" />
          </div>
          <div class="col-6">
            <label for="length" class="form-label">Length</label>
            <input type="text" class="form-control" id="length" required />
          </div>
          <div class="col-6">
            <label for="width" class="form-label">Width</label>
            <input type="text" class="form-control" id="width" required />
          </div>
          <div class="col-12">
            <button type="submit" class="btn btn-primary" id="add-blank">
              Add Blank
            </button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-2"></div>
  </div>
</div>
<hr />
<h3 class="text-center my-3">Available Blanks</h3>
<div class="container my-3">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10">
      <nav class="nav nav-pills nav-fill">
        {% for material in blank_material_names %}
        <a class="nav-link mat-butts mx-1 my-1" href="#" style="width: 30%"
          >{{ material }}</a
        >
        {% endfor %}
      </nav>
    </div>
    <div class="col-1"></div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
      <table class="table my-4 hidden" id="blanks-table">
        <thead class="thead">
          <tr>
            <th scope="col" class="text-center align-middle">Use Up</th>
            <th scope="col" class="text-center" style="width: 20%">
              <span
                >QTY <br />
                <a href="#" id="quantity-sort"
                  ><i class="fa-solid fa-arrow-down"></i></a
                >&nbsp;&nbsp;<a href="#" id="quantity-rev-sort"
                  ><i class="fa-solid fa-arrow-up"></i
                ></a>
              </span>
            </th>
            <th scope="col" class="text-center" style="width: 20%">
              <span
                >Gauge <br />
                <a href="#" id="gauge-sort"
                  ><i class="fa-solid fa-arrow-down"></i></a
                >&nbsp;&nbsp;<a href="#" id="gauge-rev-sort"
                  ><i class="fa-solid fa-arrow-up"></i
                ></a>
              </span>
            </th>
            <th scope="col" class="text-center" style="width: 20%">
              <span
                >Length <br />
                <a href="#" id="length-sort"
                  ><i class="fa-solid fa-arrow-down"></i></a
                >&nbsp;&nbsp;<a href="#" id="length-rev-sort"
                  ><i class="fa-solid fa-arrow-up"></i
                ></a>
              </span>
            </th>
            <th scope="col" class="text-center" style="width: 20%">
              <span
                >Width <br />
                <a href="#" id="width-sort"
                  ><i class="fa-solid fa-arrow-down"></i></a
                >&nbsp;&nbsp;<a href="#" id="width-rev-sort"
                  ><i class="fa-solid fa-arrow-up"></i
                ></a>
              </span>
            </th>
          </tr>
        </thead>
        <tbody id="results"></tbody>
      </table>
    </div>
    <div class="col-2"></div>
  </div>
</div>
<script src="/static/production/blanks.js"></script>
<script src="/static/production/sort.js"></script>
<script src="/static/hubs/production.js"></script>
{% endblock %}

templates/misc/create-issue.html
{% extends 'base.html' %}
{% block title%}Issue Creation{% endblock %}
{% block content %}
<div class="container my-4">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          <ul class='flashes'>
            {% for category, message in messages %}
              <div class="alert alert-{{category}} " id="flashed">
                {{ message }}
              </div>
            {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
    </div>
    <div class="col-3"></div>
  </div>
</div>
<div class="d-flex align-items-center" style="height:70vh;">
  <div class="container">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <h1 class="text-center mb-4">New Issue/Request/Bug</h1>
        <form action="{{ url_for('general.create_issue') }}"method="POST">
          {{ form.hidden_tag() }}  
          {% for field in form if field.widget.input_type != 'hidden' %}
            <div class="field">
              {{ field.label(class_='form-label') }}
              <div class="control">
                {{ field(class='form-control') }}
              </div>
            </div>
            {% for error in field.errors %}
              {{ error }}
            {% endfor %}
          {% endfor %}
          <div class="container mt-3">
            <div class="row">
              <div class="col-6 px-0">
                <button class="btn btn-primary" type="submit" style="width:100%">Create</button>  
              </div>
              <div class="col-6 px-0">
                <a href={{url_for('general.issues')}}>
                  <button class="btn btn-danger mx-1" type="button" style="width:100%;">Back</button>
                </a>
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</div>  
{% endblock %}

templates/misc/eco.html
{% extends 'base.html' %} {% block title %}ECO Explorer{% endblock %} {% block
style %}
<link
  href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css"
  rel="stylesheet"
/>
{% endblock %} {% block content %}

<div>
  <div id="wrapper"></div>
</div>

<script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
<script src="/static/production/sort.js"></script>
<script src="/static/data_explorers/eco.js"></script>
{% endblock %}

templates/misc/explorer.html
{% extends 'base.html' %} {% block title %}Data Explorer{% endblock %} {% block
style %}
<link
  href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css"
  rel="stylesheet"
/>
{% endblock %} {% block content %}

<div class="container my-3">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10">
      <nav class="nav nav-pills nav-fill" id="explorer-buttons">
        <a
          class="nav-link explorer-buttons mx-1 my-1"
          href="#"
          id="amada-button"
          style="width: 2rem"
          >Amada Laser</a
        >
        <a
          class="nav-link explorer-buttons mx-1 my-1"
          href="#"
          id="trumpf-button"
          style="width: 2rem"
          >Trumpf Laser</a
        >
        <a
          class="nav-link explorer-buttons mx-1 my-1"
          href="#"
          id="punch-button"
          style="width: 2rem"
          >Punch</a
        >
      </nav>
    </div>
    <div class="col-1"></div>
  </div>
</div>

<div>
  <div id="amada-wrapper"></div>
</div>

<div>
  <div id="trumpf-wrapper"></div>
</div>

<div>
  <div id="punch-wrapper"></div>
</div>

<script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
<script src="/static/data_explorers/explorer.js"></script>
<script src="/static/hubs/dataexplorer.js"></script>
{% endblock %}

templates/misc/issues.html
{% extends 'base.html' %}
{% block title %}Issues{% endblock %}
{% block content %}
<div class="d-flex align-items-center flex-column">
  <div class="container my-4" id="alerts">
    <div class="row">
      <div class="col-3"></div>
      <div class="col-6">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            <ul class='flashes'>
            {% for category, message in messages %}
              <div class="alert alert-{{category}} " id="flashed">
                {{ message }}
              </div>
            {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
      </div>
      <div class="col-3"></div>
    </div>
  </div>
  <h1 class="text-center mb-4">Issues/Bugs/Requests</h1>
  <div class="container my-3">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="container">
          <div class="row">
            <div class="col-6"></div>
            <div class="col-6">
                <a href={{url_for('general.create_issue')}}><button class="btn btn-primary" style="width:100%;">Add New</button></a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-1"></div>
    </div>
  </div>
  <div class="container my-3">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        <nav class="nav nav-pills nav-fill">
          <a class="nav-link mat-butts mat-butts-active mx-1" href="#" id="incomplete">Incomplete</a>
          <a class="nav-link mat-butts mx-1" href="#" id="completed">Completed</a>
        </nav>
      </div>
      <div class="col-1"></div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10" id="issues">
        {% if issues %}
          {% for issue in issues %}
            {% if issue.state == 'open' %}
              <div class="card my-3">
                <div class="container">
                  <div class="row card-header">
                    <div class="col-8">
                      <h3>{{issue.title}}</h3>
                    </div>
                    <div class="col-4">
                      <h6 class="text-center">{{issue.created_at.strftime("%m/%d/%y")}}</h6>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <p class="card-text">{{issue.body}}</p>    
                </div>
              </div>
            {% endif %}
          {% endfor %}
        {% else %}
          <h6>No pending issues!</h6>
        {% endif %}
      </div>
      <div class="col-1"></div>
    </div>
  </div>
  <span class="text-center my-5">Something else? <a href="mailto:alex-m-howard@pm.me?subject=Production Site">Contact Me</a></span>
</div>
<script src="/static/general/issues.js"></script>
{% endblock %}

templates/misc/requests.html
{% extends 'base.html' %} {% block title %}Programming Request{% endblock %} {%
block content %}

<div id="alerts"></div>

<h1 class="text-center my-5">Programming Request</h1>
<div class="container mb-5">
  <div class="row">
    <div class="col-lg-3 col-sm-0"></div>
    <div class="col-lg-6 col-sm-12">
      <form action="{{url_for('requests.requesting')}}" method="post">
        {{ form.hidden_tag() }}  
          {% for field in form
                  if field.widget.input_type != 'hidden' %}

                <div class="field">
                  {{ field.label(class_='form-label') }}
                  <div class="control">
                  {{ field(class='form-control') }}
                  </div>
                </div>
                {% for error in field.errors %}
                  {{ error }}
                {% endfor %}
              </p>

            {% endfor %}
          

          <div class="row">
            <div class="col-lg-4 col-sm-0"></div>
            <div class="col-lg-4 col-sm-12">
              <button class="btn btn-primary" type="submit" style="width:100%;" id="submit">Add</button>
            </div>
            <div class="col-lg-4 col-sm-0"></div>
          </div>
      </form>
    </div>
    <div class="col-lg-3 col-sm-0"></div>
  </div>
</div>
   <hr>
    <h3 class="text-center my-3 mt-5">Current Requests</h3>
    
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-3"></div>
        <div class="col-lg-2 col-3 request-success mx-1 text-center">Complete</div>
        <div class="col-lg-2 col-3 request-danger mx-1 text-center">Incomplete</div>
        <div class="col-lg-4 col-3"></div>
      </div>
    </div>
    
    <div class="container mb-5">
        <div class="row">
            <div class="col-lg-2 col-sm-0"></div>
            <div class="col-lg-8 col-sm-12">
                <table class="table my-4 table-responsive" id="requests-table">
                    <thead class="thead"> 
                        <tr>
                            <th scope="col" class="text-center"  style="width:20%">
                                <span>Type</span>
                            </th>
                            <th scope="col" class="text-center"  style="width:20%">
                                <span>Part/Program</span>
                            </th>
                            <th scope="col" class="text-center" style="width:45%">
                                <span>Description</span>
                            </th>
                            <th scope="col" class="text-center"  style="width:15%">
                                <span>Requested By</span>
                            </th>
                            <th scope="col" class="text-center"  style="width:15%">
                                <span>Job Number</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="results">
                        {% for request in requests %}
                          {% if not request.date_completed %}
                            <tr class="request-danger">
                              <td class="text-center" data-request_id={{request.id}}>{{request.request_type}}</td>
                              <td class="text-center">{{request.to_change}}</td>
                              <td class="text-center">{{request.description}}</td>
                              <td class="text-center">{{request.requested_by}}</td>
                              <td class="text-center">{{request.job_number}}</td>
                          {% else %}
                          <tr class="request-success">
                              <td class="text-center">{{request.request_type}}</td>
                              <td class="text-center">{{request.to_change}}</td>
                              <td class="text-center">{{request.description}}</td>
                              <td class="text-center">{{request.requested_by}}</td>
                              <td class="text-center">{{request.job_number}}</td>
                          {% endif %}
                          {% if not g.user.role == 'user' and not g.user.role == 'prod' %}
                            <td class="text-center">
                              <input type="text" name="job_number" id="job_number">
                            </td>
                            <td class="text-center">
                              <button class="btn btn-primary complete-btn" type="submit" style="width:100%;">Complete</button>
                            </td>                  
                          {% endif %}
                          </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-2 col-sm-0"></div>
        </div>
    </div>
<script src="/static/production/request.js"></script>
<script src="/static/hubs/production.js"></script>

{% endblock %}

templates/misc/todo.html
{% extends 'base.html' %}
{% block title %}TODOs{% endblock %}
{% block content %}
    <h1 class="text-center my-5">Still To-Do</h1>
    <div class="container my-5">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <ul>
                    <li style="text-decoration:line-through">Transfer Work done on Amada table to Trumpf</li>
                    <li style="text-decoration:line-through">Transfer Work done on Amada table to Punch</li>
                    <li style="text-decoration:line-through">Style to be more appealing than a geocities site</li>
                    <li style="text-decoration:line-through">Create home landing page so that people don't sit through loading of page they won't use</li>
                    <li style="text-decoration:line-through">Add Amada SOPs</li>
                    <li style="text-decoration:line-through">Add Trumpf SOPs</li>
                    <li style="text-decoration:line-through">Add Punch SOPs</li>
                    <li style="text-decoration:line-through">Add Forming SOPs</li>
                    <li style="text-decoration:line-through">Add Nesting Calculator</li>
                    <li style="text-decoration:line-through">Reduce Python API Data-Explorer Data call time  ~1.2 seconds -> ~.005 seconds</li>
                    <li style="text-decoration:line-through">Reduce Python API ECO Data call time  ~1.4 seconds -> ~.03 seconds</li>
                    <li style="text-decoration:line-through">Reduce JavaScript API ECO Data call time  ~1.2 seconds -> ~.13 (Because of Python gains)</li>
                    <li style="text-decoration:line-through">Reduce JavaScript createTableFunction  ~.8 seconds -> ~.2 (Total time for page load ~.5seconds)</li>
                    <li style="text-decoration:line-through">Combine JS filtering in smaller function</li>
                    <li style="text-decoration:line-through">Add viewable ECO database</li>
                    <li style="text-decoration:line-through">Add part program status to home page</li>
                    <li style="text-decoration:line-through">Add parts explorer</li>
                    <li style="text-decoration:line-through">Add blanks inventory</li>
                    <li style="text-decoration:line-through">Create watchdog for any changes to ECO data in programming folder</li>
                    <li style="text-decoration:line-through">Add something to visualize obsolete parts in ECO viewer</li>
                    <li style="text-decoration:line-through">Jaron -> Add identifier for pending eco parts in incomplete programs view</li>
                    <li style="text-decoration:line-through">Add hamburger menu when website sized down</li>
                    <li style="text-decoration:line-through">Add  logo as brand instead of absolute image</li>
                    <li style="text-decoration:line-through">Added preliminary prototype log</li>
                </ul>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
    <h1 class="text-center my-5">User Requests</h1>
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <form action="/todo" method="post">
                    <div class="container">
                        <div class="row">
                            <div class="col-2">
                                <input class="form-control" type="text" placeholder="Name" name="name">
                            </div>
                            <div class="col-10">
                                <input class="form-control" type="text" placeholder="Bug? Suggestion? Let me know!" name="request">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary my-3" id="submit-request">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="container my-3">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <ul>
                    {% if requests%}
                        {% for request in requests %}
                            <li>{{ request.user }} : {{ request.request }}</li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
{% endblock %}