models/error.py
from flask import jsonify

from db import db

class Error(db.Model):
    """ 
    Error MODEL

    """
    
    __tablename__ = 'errors'

    id = db.Column(db.Integer, primary_key=True)
    part_number = db.Column(db.String)
    date = db.Column(db.Date, nullable=False)
    machine = db.Column(db.String)
    description = db.Column(db.String, nullable=False)
    root_cause = db.Column(db.String)
    notes = db.Column(db.String)
    name = db.Column(db.String)
    
    def __repr__(self): 
        return f"<Error #: {self.id}, Date: {self.date}, Description: {self.description}>"

    @staticmethod
    def many_to_json(data):
        errors = []
        
        for error in data:
            errors.append({
                "id" : error.id,
                "part_number": error.part_number,
                "description": error.description,
                "date" : error.date,
                "machine" : error.machine,
                "root_cause" : error.root_cause,
                "notes" : error.notes,
                "name" : error.name
            })
            
        return errors

routes/amada.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, g, jsonify, request, send_file

from models.nest import Nest, Machine

amada = Blueprint(
    'amada',
    __name__,
    static_folder='../../static',
    template_folder='../../templates/app',
    url_prefix='/amada'
    )


@amada.route("/")
def amada_home():
    return render_template("hubs/amada.html")

@amada.route("/data")
def get_amada_data():
    machine_id = Machine.query.filter_by(name='Amada', machine_type='Laser').one().id
    nests = Nest.query.filter_by(machine_id=machine_id).all()
    nests = Nest.many_to_json(nests)
    
    return nests

@amada.route("/blankcam")
def amada_blankcam():
    return render_template("sops/blankcam.html")

@amada.route("/data_explorer_sop")
def data_explorer():
    return render_template("sops/data_explorer.html")

@amada.route("/material_explorer_sop")
def material_explorer():
    return render_template("sops/material_explorer.html")

@amada.route("/parameter_explorer_sop")
def parameter_explorer():
    return render_template("sops/parameter_explorer.html")

routes/errors.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, g, jsonify, request, send_file
from db import db

from models.error import Error
from models.file import File
from models.forms import AddError, EditError

from datetime import datetime
from utilities import upload_error_file, list_all_objects_version, create_presigned_url

errors = Blueprint(
    'errors',
    __name__,
    static_folder='../../static',
    template_folder='../../templates/app',
    url_prefix='/errors'
    )


@errors.route("/")
def error_log():
    errors = Error.query.order_by(Error.date.desc()).all()
    
    for error in errors:
        error.date = error.date.strftime("%m/%d/%Y")
        
    return render_template("/error_log/error-log.html", errors=errors)    


@errors.route("/data")
def get_data():
    
    errors = Error.query.order_by(Error.date.desc()).all()
    errors = Error.many_to_json(errors)
    
    return errors


@errors.route("/add", methods=["GET", "POST"])
def add_to_errors():
    
    form = AddError()
    
    if form.validate_on_submit():
        
        new_error = Error(
            part_number = form.part_number.data,
            date = datetime.today().strftime("%m-%d-%Y"),
            machine = form.machine.data,
            description = form.description.data,
            root_cause = form.root_cause.data,
            notes = form.notes.data,
            name = form.name.data
        )
        
        db.session.add(new_error)
        db.session.commit()
        
        return redirect(url_for('errors.error_log'))
    
    return render_template("/error_log/add-error.html", form=form)


@errors.route("/edit/<error_id>", methods=["GET", "POST"])
def edit_error(error_id):
    
    error = Error.query.filter_by(id=error_id).one()
    
    form = EditError(obj=error)
    
    if form.validate_on_submit():
       
        error.part_number = form.part_number.data or error.part_number,
        error.machine = form.machine.data or error.machine,
        error.description = form.description.data or error.description,
        error.root_cause = form.root_cause.data or error.root_cause,
        error.notes = form.notes.data or error.notes,
        error.name = form.name.data or error.name
         
        db.session.commit()
        
        return redirect(url_for('errors.show_error', id=error_id))
    
    return render_template("/error_log/edit-error.html", form=form, error_id=error.id)


@errors.route("/<id>")
def show_error(id):
    
    error = Error.query.filter_by(id=id).one()
    files = File.query.filter_by(error_id=id).all()
    
    for file in files:
        # Create presigned URLS
        file.presigned_url = create_presigned_url(file.file_name, file.version)
        
    return render_template('/error_log/error.html', error=error, files=files)


@errors.route("/<id>/add", methods=["GET", "POST"])
def add_file(id):
    if request.method=="POST" :
        try:
            files = request.files.getlist('images')
            
            for file in files:
                upload_error_file(file=file, filename=file.filename)
                
                response = list_all_objects_version(file.filename)
                new_file = File(file_name=file.filename, error_id=id)
                
                try:
                    new_file.version = response["Versions"][0]["VersionId"]
                except:
                    new_file.version = '0'
                
                db.session.add(new_file)
                db.session.commit()

        except Exception as e:
            print(e)
            
        return redirect(url_for('errors.show_error', id=id))
    return render_template('/error_log/add-file.html', id=id)

routes/punch.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, g, jsonify, request, send_file

from models.nest import Nest, Machine

punch = Blueprint(
    'punch',
    __name__,
    static_folder='../../static',
    template_folder='../../templates/app',
    url_prefix='/punch'
    )


@punch.route("/")
def punch_home():
    return render_template("hubs/punch.html")

@punch.route("/data")
def get_punch_data():
    machine_id = Machine.query.filter_by(
        name='Murata', machine_type='Punch').one().id
    nests = Nest.query.filter_by(machine_id=machine_id).all()
    nests = Nest.many_to_json(nests)

    return nests

@punch.route("/sop")
def punch_sop():
    return render_template("sops/punch_sop.html")

routes/trumpf.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, g, jsonify, request, send_file

from models.nest import Nest, Machine 

trumpf = Blueprint(
    'trumpf',
    __name__,
    static_folder='../../static',
    template_folder='../../templates/app',
    url_prefix='/trumpf'
    )


@trumpf.route("/")
def trumpf_home():
    return render_template("hubs/trumpf.html")

@trumpf.route("/data")
def get_trumpf_data():
    machine_id = Machine.query.filter_by(
        name='Trumpf', machine_type='Laser').one().id
    nests = Nest.query.filter_by(machine_id=machine_id).all()
    nests = Nest.many_to_json(nests)

    return nests

@trumpf.route("/trutops")
def trumpf_trutops():
    return render_template("sops/trutops.html")

@trumpf.route("/offline_loading")
def trumpf_offline_loading():
    return render_template("sops/offline_loading.html")

routes/user.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, g, jsonify, request
from sqlalchemy.exc import IntegrityError

from db import db

from models.user import User
from models.forms import SignupForm, LoginForm

from routes.amada import amada
from routes.punch import punch
from routes.trumpf import trumpf
from routes.forming import forming
from routes.requests import requests
from routes.general import general
from routes.errors import errors
from routes.seed import seed
from routes.documentation import docs
from routes.prototypes import proto

from random import random

from utilities import send_temp_email

current_user_id = 'current_user_id'

user = Blueprint(
    'user',
    __name__,
    static_folder='../static',
    template_folder='../templates/user',
    url_prefix='/user'
)


# # # # # # # # # # # # # # # # # # # #
#                                     #
# User signup and login authorization #
#                                     #
# # # # # # # # # # # # # # # # # # # #

@user.route('/signup', methods=["GET", "POST"])
def signup_page():
    """ Show sign up form - Validate and create user upon success - Reject and redo on failure """

    if current_user_id in session:
        return redirect(url_for('home'))

    form = SignupForm()

    if request.method == "POST":

        temp_password = str(random())[2:8]

        try:
            user = User.signup(
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                password=temp_password,
                email=form.email.data.lower()
            )

            db.session.commit()

        except IntegrityError:
            flash("Username/Email already exists", 'danger')
            return render_template('/user/sign_up.html', form=form)

        except Exception as err:
            flash("Unknown error has occurred. Try again later", 'danger')
            print(err)
            return render_template('/user/sign_up.html', form=form)

        flash('Please check your email for your temporary password', "success")
        session['email'] = form.email.data.lower()
        send_temp_email(session["email"], temp_password)
        session["code"] = temp_password
        
        return redirect(url_for('user.check_code'))

    if request.method == "GET":
        return render_template('/user/sign_up.html', form=form)


@user.route('/login', methods=["GET", "POST"])
def login_page():
    """ Show login form """
    
    if current_user_id in session:
        return redirect(url_for('home'))

    if request.method == "GET":
        return render_template('/user/login.html')

    if request.method == "POST":
        email = request.form.get('email').lower()
        
        user = User.authenticate(
            email=email,
            password=request.form.get('password')
        )

        print(request.form)
        

        if user:
            do_login(user)
            session['email'] = email
            flash(f"Hello, {user.first_name}!", "success")

            return redirect(url_for('home'))
        else:
            flash("Invalid Credentials.", "danger")
            return redirect(url_for('user.login_page'))


@user.route('/logout', methods=["GET"])
def logout_user():
    """Initiate Logout"""

    do_logout()
    flash('Successfully signed out', 'success')

    return redirect(url_for('user.login_page'))


@user.route('/verification', methods=["GET", "POST"])
def check_code():
    if request.method == "GET":
        return render_template('/user/verification.html', email=session['email'], code=session['code'])

    if request.method == "POST":

        code = request.form.get('1') + request.form.get('2') + request.form.get(
            '3') + request.form.get('4') + request.form.get('5') + request.form.get('6')

        user = User.authenticate(
            email=session['email'],
            password=code)

        if user:
            return render_template('/user/change_password.html')
        else:
            flash("Invalid verification code. Please try again.", "danger")
            return render_template('/user/verification.html', email=session['email'])


def do_login(user):
    """ Log in user """

    session[current_user_id] = user.id


def do_logout():
    """ Log out current user """

    if current_user_id in session:
        del session[current_user_id]

    g.user = None


@user.route('/change-password', methods=["GET", "POST"])
def change_password():
    if g.user.id == 4:
        return redirect(url_for('home')) # Guest user shouldn't change password
    
    if request.method == "GET":
        return render_template('/user/change_password.html')

    if request.method == "POST":

        user = User.new_password(
            session["email"], request.form.get('password'))

        do_login(user)
        flash(f"Password successfully changed!", "success")
        return redirect(url_for('home'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://kit.fontawesome.com/22a73e52cb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/static/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="/static/styles.css">
    {% block style %}{% endblock %}
</head>
<body class="hidden">
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="nav-link" href="/">
        <img src="/static/images/dark_banner-noback.png" alt="Bootstrap" class="navbar-brand" id="alex-logo">
      </a>
      <button id='hamburger-button' class="navbar-toggler mx-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa-solid fa-bars me-5" id="hamburger"></i>
      </button>

      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        {% if g.user %}
        <ul class="navbar-nav mb-2 mb-lg-0 mx-auto">
          <li class="nav-item mx-3"><a class="nav-link" href="/" id="Home-nav">Dashboard</a></li>
          <div class="navbar-item dropdown">
            <button class="btn dropdown-toggle" id="dropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="border-color: #002856;">
              SOPs
            </button>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{{url_for('amada.amada_home')}}" id="nav-drop">Amada</a>
                <ul class="dropdown-menu dropdown-submenu">
                  <li><a class="dropdown-item" href="{{url_for('amada.amada_blankcam')}}" id="nav-drop">Blank CAM SOP</a></li>
                  <li><a class="dropdown-item" href="{{url_for('amada.data_explorer')}}" id="nav-drop">Data Explorer Guide</a></li>
                  <li><a class="dropdown-item" href="{{url_for('amada.material_explorer')}}" id="nav-drop">Material Explorer Guide</a></li>
                  <li><a class="dropdown-item" href="{{url_for('amada.parameter_explorer')}}" id="nav-drop">Parameter Explorer Guide</a></li>
                </ul>
              </li>
              <li>
                <a class="dropdown-item" href="{{url_for('trumpf.trumpf_home')}}" id="nav-drop">Trumpf</a>
                <ul class="dropdown-menu dropdown-submenu">
                  <li><a class="dropdown-item" href="{{url_for('trumpf.trumpf_trutops')}}" id="nav-drop">Tru-Tops SOP</a></li>
                  <li><a class="dropdown-item" href="{{url_for('trumpf.trumpf_offline_loading')}}" id="nav-drop">Offline Program Loading SOP</a></li>
                </ul>
              </li>
              <li>
                <a class="dropdown-item" href="{{url_for('punch.punch_home')}}" id="nav-drop">Punch</a>
                <ul class="dropdown-menu dropdown-submenu">
                  <li><a class="dropdown-item" href="{{url_for('punch.punch_sop')}}" id="nav-drop">Punch SOP</a></li>
                  <li><a class="dropdown-item" href="http://mmisupport.com/HelpSys/smphelp/index.htm" id="nav-drop">SMP Master Index</a></li>
                </ul>
              </li>
              <li>
                <a class="dropdown-item" href="{{url_for('forming.forming_home')}}" id="nav-drop">Forming</a>
                <ul class="dropdown-menu dropdown-submenu">
                  <li><a class="dropdown-item" href="{{url_for('forming.forming_bend_operation')}}" id="nav-drop">Amada Bend Operation</a></li>
                  <li><a class="dropdown-item" href="{{url_for('forming.forming_bend_params')}}" id="nav-drop">Amada Bend Parameters</a></li>
                  <li><a class="dropdown-item" href="{{url_for('forming.forming_bend_users')}}" id="nav-drop">Amada Bend User Guide</a></li>
                  <li><a class="dropdown-item" href="{{url_for('forming.data_explorer')}}" id="nav-drop">Data Explorer Guide</a></li>
                  <li><a class="dropdown-item" href="{{url_for('forming.material_explorer')}}" id="nav-drop">Material Explorer Guide</a></li>
                  <li><a class="dropdown-item" href="{{url_for('forming.parameter_explorer')}}" id="nav-drop">Parameter Explorer Guide</a></li>
                  <li><a class="dropdown-item" href="{{url_for('forming.forming_salvagnini_guide')}}" id="nav-drop">Salvagnini Users Guide</a></li>
                </ul>
              </li>
            </ul>
          </div>
          
          <div class="navbar-item dropdown">
            <button class="btn dropdown-toggle" id="dropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="border-color: #002856;">
              Production
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{url_for('general.blanks_inventory')}}" id="nav-drop">Blanks Inventory</a></li>
              <li><a class="dropdown-item" href="{{url_for('requests.requesting')}}" id="nav-drop">Programming Requests</a></li>
              <li><a class="dropdown-item" href="{{url_for('errors.error_log')}}" id="nav-drop">Error Log</a></li>
            </ul>
          </div>
          
          <div class="navbar-item dropdown">
            <button class="btn dropdown-toggle" id="dropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="border-color: #002856;">
              Prototypes
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{url_for('proto.show_my_projects')}}" id="nav-drop">My Projects</a></li>
              <li><a class="dropdown-item" href="{{url_for('proto.show_projects')}}" id="nav-drop">All Projects</a></li>
            </ul>
          </div>
          
          <li><a class="nav-link" href="{{url_for('general.eco_viewer')}}" id="eco-nav">ECO Viewer</a></li>
          <li><a class="nav-link" href="{{url_for('general.nesting_calculator')}}" id="nestCalc-nav">Nesting Calculator</a></li>
        </ul>
        {% endif %}
      </div>

      <div class="d-flex align-items-center ms-3">
        {% if g.user %}
        <div class="dropdown" id="user-menu">
          <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">{{ g.user.first_name }}</a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item" href="{{ url_for('proto.show_my_projects')}}">My Projects</a></li>
            {% if g.user.first_name != 'Guest' %}
            <li><a class="dropdown-item" href="{{ url_for('user.change_password')}}">Change Password</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="{{ url_for('user.logout_user') }}">Logout</a></li>
          </ul>

          
        </div>
        {% else %}
          <a href="{{ url_for('user.login_page') }}" class="nav-link">Login</a>
        {% endif %}
      </div>



    </div>
  </nav>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="/static/bootstrap/bootstrap.bundle.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  {% block content %}{% endblock %}

  <footer id="sticky-footer">
    {% if g.user %}
    <div class="container">
          <a href="{{ url_for('docs.home') }}" style="color:white; text-decoration:none;">Documentation</a>
    </div>
    <div class="container">
    </div>
    <div class="container text-center">
          For bugs, issues, or requests: <a href="{{url_for('general.issues')}}" style="color:white;">Issues</a> 
    </div>
    {% endif %}
  </footer>
  <script src="/static/app.js"></script>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% block title %}Projects{% endblock %}

{% block content %}

<div class="container my-4" id="alerts">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          <ul class='flashes'>
          {% for category, message in messages %}
            <div class="alert alert-{{category}} " id="flashed">
              {{ message }}
            </div>
          {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
    </div>
    <div class="col-3"></div>
  </div>
</div>

 <h3 class="text-center my-3 mt-5">Current Programming Requests</h3>
    
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-3"></div>
        <div class="col-lg-2 col-3 request-success mx-1 text-center">Complete</div>
        <div class="col-lg-2 col-3 request-danger mx-1 text-center">Incomplete</div>
        <div class="col-lg-4 col-3"></div>
      </div>
    </div>
    
    {% if requests %}
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-sm-0"></div>
            <div class="col-lg-8 col-sm-12">
                <table class="table my-4 table-responsive" id="requests-table">
                    <thead class="thead"> 
                        <tr>
                            <th scope="col" class="text-center"  style="width:20%">
                                <span>Type</span>
                            </th>
                            <th scope="col" class="text-center"  style="width:20%">
                                <span>Part/Program</span>
                            </th>
                            <th scope="col" class="text-center" style="width:45%">
                                <span>Description</span>
                            </th>
                            <th scope="col" class="text-center"  style="width:15%">
                                <span>Requested By</span>
                            </th>
                            <th scope="col" class="text-center"  style="width:15%">
                                <span>Job Number</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="results">
                        {% for request in requests %}
                          {% if not request.date_completed %}
                            <tr class="request-danger">
                              <td class="text-center" data-request_id={{request.id}}>{{request.request_type}}</td>
                              <td class="text-center">{{request.to_change}}</td>
                              <td class="text-center">{{request.description}}</td>
                              <td class="text-center">{{request.requested_by}}</td>
                              <td class="text-center">{{request.job_number}}</td>
                          {% else %}
                          <tr class="request-success">
                              <td class="text-center">{{request.request_type}}</td>
                              <td class="text-center">{{request.to_change}}</td>
                              <td class="text-center">{{request.description}}</td>
                              <td class="text-center">{{request.requested_by}}</td>
                              <td class="text-center">{{request.job_number}}</td>

                            
                          {% endif %}
                          
                          </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-2 col-sm-0"></div>
        </div>
    </div>
    {% else %} 
      <h4 class="text-center my-5">No Requests</h4>
    {% endif %}

  

<hr class="my-5" >

<h3 class="text-center my-3">Prototype Dashboard</h3>
{% if projects %}
<div class="container">
    <div class="row my-2">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="card" >
                <div class="card-body">
                    <h5 class="card-title text-center">On Time</h5>
                    <div class="table-responsive">
                        <table class="table my-3 table-hover">
                            <thead>
                                <tr>
                                <th scope="col" class="text-center">Project Name</th>
                                <th scope="col" class="text-center">Last Updated</th>
                                <th scope="col" class="text-center">By</th>
                                <th scope="col" class="text-center">Progress</th>
                                <th scope="col" class="text-center">Projected Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for project in projects %}
                                    {% if project.status == 'Incomplete' %}
                                        {% if not project.late %}
                                            <tr>
                                                <th scope="row" class="text-center"><a href="{{ url_for('proto.show_project', project_name=project.project_name) }}">{{ project.project_name}}</a></td>
                                                {% if project.updated %}
                                                    <td class="text-center">{{ project.updated.strftime('%m-%d-%Y')}}</td>    
                                                {% else %}
                                                    <td class="text-center">{{ project.updated}}</td>    
                                                {% endif %}
                                                    <td class="text-center">{{ project.updated_by }}</td>
                                                    <td class="text-center">
                                                    <div class="progress">
                                                        <div class="progress-bar bg-primary" role="progressbar" style="width: {{project.progress}}%" aria-valuenow="{{ project.progress }}" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </td>
                                                {% if project.date_requested %}
                                                    <td class="text-center">{{ project.date_requested.strftime('%m-%d-%Y')}}</td>    
                                                {% else %}
                                                    <td class="text-center">{{ project.date_requested}}</td>    
                                                {% endif %}
                                            </tr>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="col-1"></div>
    </div>
</div>

<div class="container">
    <div class="row my-5">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="card" >
                <div class="card-body">
                    <h5 class="card-title text-center">Past Due</h5>
                    <div class="table-responsive">
                        <table class="table my-3 table-hover">
                            <thead>
                                <tr>
                                <th scope="col" class="text-center">Project Name</th>
                                <th scope="col" class="text-center">Last Updated</th>
                                <th scope="col" class="text-center">By</th>
                                <th scope="col" class="text-center">Progress</th>
                                <th scope="col" class="text-center">Projected Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for project in projects %}
                                    {% if project.status == 'Incomplete' %}
                                        {% if project.late %}
                                            <tr>
                                                <th scope="row" class="text-center"><a href="{{ url_for('proto.show_project', project_name=project.project_name) }}">{{ project.project_name}}</a></td>
                                                {% if project.updated %}
                                                    <td class="text-center">{{ project.updated.strftime('%m-%d-%Y')}}</td>    
                                                {% else %}
                                                    <td class="text-center">{{ project.updated}}</td>    
                                                {% endif %}
                                                <td class="text-center">{{ project.updated_by }}</td>
                                                <td class="text-center">
                                                    <div class="progress">
                                                        <div class="progress-bar bg-danger" style="width: {{project.progress}}%" role="progressbar" aria-valuenow="{{project.progress}}" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </td>
                                                {% if project.date_requested %}
                                                    <td class="text-center">{{ project.date_requested.strftime('%m-%d-%Y')}}</td>    
                                                {% else %}
                                                    <td class="text-center">{{ project.date_requested}}</td>    
                                                {% endif %}
                                            </tr>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="col-1"></div>
    </div>
</div>
{% else %}
    <h3 class="text-center my-5">No projects to show</h3>
{% endif %}



<script src="/static/production/request.js"></script>
<script src="/static/hubs/home.js"></script>
{% endblock %}

templates/resume.html
{% extends 'base.html' %}
{% block title %}Alex Howard Resume{% endblock %}
{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <iframe class="mt-5" src="https://resume.creddle.io/embed/4r3me2zb6t7"
  width="850" height="1100" seamless></iframe>
        </div>
        <div class="col-1"></div>
    </div>
</div>


{% endblock %}